version: '3.8'
x-vars: &base-vars
  VERSION: ${VERSION}
  IMAGE: ${IMAGE}
  APP_NAME: ${APP_NAME}
services:
  api:
    container_name: ${APP_NAME}_api
    image: "${CI_REGISTRY_IMAGE-local}/${APP_NAME}:${CI_COMMIT_SHORT_SHA-local}"
    build:
      args: 
        << : *base-vars
    environment:
      << : *base-vars
    command: echo ${APP_NAME} is running