version: '3.8'
x-vars: &base-vars
  APP_NAME: ${APP_NAME}
  IMAGE: ${IMAGE}
  IMAGE_VERSION: ${IMAGE_VERSION}
  IMAGE_TYPE: ${IMAGE_TYPE}
services:
  api:
    container_name: ${APP_NAME}_api
    image: "${CI_REGISTRY_IMAGE-local}/${APP_NAME}:${CI_COMMIT_SHORT_SHA-local}"
    build:
      context: ../dockerfile/
      dockerfile: Dockerfile-python
      args: 
        << : *base-vars
    environment:
      << : *base-vars
    command: echo ${APP_NAME} is running